name:  Run on push

on:  [push]

jobs:
  simple-job:
    runs-on:  ubuntu-latest
    steps: 
      - name:  Checkout code
        uses:  actions/checkout@v3

      - name:  List files
        run:  ls -R
