name: Docker with Secret

on:
  workflow_dispatch

jobs:
  docker-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t secret-image ./docker-secret-demo

      - name: Run Docker container with secret
        run: docker run -e MY_SECRET=${{ secrets.MY_SECRET }} secret-image
