name: Python with Secret

on:
  workflow_dispatch

jobs:
  secret-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Access secret
        run: |
          echo "using secret value...."
          echo "secret: ${{ secrets.MY_SECRET }}">>secret_used.log
          cat secret_used.log

      - name: Upload Secret log
        uses: actions/upload-atifact@v4
        with:
          name: secret-log
          path: secret_used.log
