name:  Python CI + Simulated CD

on:
  workflow_dispatch:
    branches: ["main"]
    paths:
      - "**.py"
      - "requirements.txt"
      - ".github/workflows/python-app2.yml" 

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.10", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulate deployment
        run: |
          echo "Deployed by ${{ github.actor }} after all tests passed ">deployment.log
          cat deployment.log

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deployment-log
          path: deployment.log
