name: python pipeline

on:
  push:
    branches: ["main"]
    paths:
      - "**.py"
      - ".github/workflows/python-ci-cd.yml"
      
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkoutcode
        uses: actions/checkout@v4
        
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          
      - name: Install flake8
        run: pip install flake8
      - name: Lint code
        run: flake8 .
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v5
        with: 
          python-version: "3.12"
      - name: Run tests
        run: pytest test_main.py

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cretae build artifact
        run: |
          mkdir build
          cp main.py build/
          ip -r build/main_app.zip build/
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app-build
          path: build/main_app.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Simulate deployment
        run: |
          echo "Deployed successfully by ${{ github.actor }} ">deploy.log
          cat deploy.log
      - name: Upload deployment.log
        uses: actions/upload-artifact@v4
        with:
          name: deploy-log
          path: deploy.log          